### ISSUE TITLE
How to switch different packages in dev module

### ISSUE THREAD

**Issue by cpdtzy** [crashmax-dev/fireworks-js#100]
### Issue

I run `npm run dev`.
And I have open browser of this url for  http://127.0.0.1:8081/. But It were svelte package, I don't know how to switch different package.

**Comment by crashmax-dev** [comment]
In the folder with [examples](https://github.com/crashmax-dev/fireworks-js/tree/master/examples) there are applications

**Comment by cpdtzy** [comment]
Like I copy with react's files to package react and modify package.json file. The `vite build --watch` to `vite dev --port 8081 --open` ?

**Comment by cpdtzy** [comment]
> In the folder with [examples](https://github.com/crashmax-dev/fireworks-js/tree/master/examples) there are applications

Like I copy with react's files to package react and modify package.json file. The vite build --watch to vite dev --port 8081 --open ?

**Comment by cpdtzy** [comment]
> > In the folder with [examples](https://github.com/crashmax-dev/fireworks-js/tree/master/examples) there are applications
> 
> Like I copy with react's files to package react and modify package.json file. The vite build --watch to vite dev --port 8081 --open ?

Or other port ?

**Comment by cpdtzy** [comment]
I got it. Thanks
