### ISSUE TITLE
[react] - Is it possible to load toggled off?

### ISSUE THREAD

**Issue by thesciz** [crashmax-dev/fireworks-js#109]
### Issue

By default the fireworks start on load; I'd like to only start them on demand (and not have to immediately call .stop() on load). 

Is this currently possible?

**Comment by crashmax-dev** [comment]
on demand launch fireworks: https://codesandbox.io/s/fireworks-js-react-autostart-false-3zjvo7?file=/src/App.tsx

**Comment by thesciz** [comment]
Thanks! Did I miss that in the docs or is it relatively new?

**Comment by crashmax-dev** [comment]
> Thanks! Did I miss that in the docs or is it relatively new?

it was always there, there is just no description in the readme  :eyes:
