### ISSUE TITLE
simple js file

### ISSUE THREAD

**Issue by aaron13100** [crashmax-dev/fireworks-js#116]
### Issue

Hello. Not an issue..
What are the chances of making a simple .js file available?  I've tried building this myself and have had many various issues as I don't know what I'm doing. I understand there are .js files via the CDN links in the readme file. I'm hoping for non-minimized, non-obfuscated versions so I can make changes.

thanks

**Comment by aaron13100** [comment]
No longer needed for my specific use-case, but still nice to have (and for next time). I'm also using version 1.3.3 and I'm stuck there.

**Comment by crashmax-dev** [comment]
> No longer needed for my specific use-case, but still nice to have (and for next time). I'm also using version 1.3.3 and I'm stuck there.

Why don't you use the latest version?
Anyway, im rebuilded the code without minification https://gist.github.com/crashmax-dev/0e686a9f790bd59384272421d9d5c64f

**Comment by aaron13100** [comment]
Thank you!  I couldn't find the latest version non-minified and I've made changes to the version I have that I'll want to make to the new version also.  So I had the old version because modifying a minified version is a pain.

I guess you'll ask me what changes I've made. So here they are.
* pass in the number of fireworks that will go off. eg fireworks.start(1) sets off just 1 and stops. fireworks.start(10) sets off 10 and then stops.
* use my own function to play audio so I can adjust the volume and follow whether it's playing or not.
* wait to load the audioContext until initTrace() so there's no warning about missing user interaction in Firefox.

**Comment by crashmax-dev** [comment]
> * pass in the number of fireworks that will go off. eg fireworks.start(1) sets off just 1 and stops. fireworks.start(10) sets off 10 and then stops.

https://github.com/crashmax-dev/fireworks-js#launchcount

You don't want to create a pr merge?
