### ISSUE TITLE
Respect prefers-reduced-motion

### ISSUE THREAD

**Issue by mrankine** [crashmax-dev/fireworks-js#120]
### Description

As far as I can tell with Chrome Dev Tools, this library doesn't respect a user's preference to set [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).

Should it?

### Which package are you using?

fireworks-js, @fireworks-js/svelte

### fireworks-js version

2.10.7

### Browser

Chrome - Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by mrankine** [comment]
I suppose you can just hide the fireworks container with a media query CSS rule, but that feels suboptimal.

**Comment by crashmax-dev** [comment]
@mrankine Hi! I don't think that is the library responsibility.

**Comment by mrankine** [comment]
Fair enough 😊
