### ISSUE TITLE
Build warning: "The following packages have a svelte field in their package.json but no exports condition for svelte"

### ISSUE THREAD

**Issue by mrankine** [crashmax-dev/fireworks-js#121]
### Description

I get this warning on building. The [docs](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition) advise to report it to package maintainers as it will break in future versions of vite.
```
08:58:58 [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

@fireworks-js/svelte@2.10.7

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

### Which package are you using?

@fireworks-js/svelte

### fireworks-js version

2.10.7

### Browser

vite/5.3.3 linux-x64 node-v20.14.0

**Comment by crashmax-dev** [comment]
@mrankine fixed on 2.10.8
