### ISSUE TITLE
React cleanup on event listener is not happening on unmount

### ISSUE THREAD

**Issue by asim-aashish** [crashmax-dev/fireworks-js#34]
[This](https://github.com/crashmax-dev/fireworks-js/blob/cfe9620304ecbb60989eac81b1732b2f867f0576/src/fireworks.ts#L133) autosize listener is not cleared when react unmount is [called](https://github.com/crashmax-dev/fireworks-js/blob/master/src/fireworks.ts#L159)

**Comment by crashmax-dev** [comment]
@asim-aashish Thanks for issues! Well. This will be to next update.
