### ISSUE TITLE
Error when building Next project

### ISSUE THREAD

**Issue by maksepsteins** [crashmax-dev/fireworks-js#51]
Due to the type imports in react.d.ts the project crashes when building Next project. 
Works if import is done like this:
`import type { FireworksOptions } from './fireworks';`
instead of:
import { type FireworksOptions } from './fireworks';
I have TS version 4.4.4 and next 12.1.4

**Comment by crashmax-dev** [comment]
Hi, that's not where you're importing from

```js
import type { FireworksProps } from 'fireworks-js/dist/react'
// or
import { type FireworksProps } from 'fireworks-js/dist/react'
```
