### ISSUE TITLE
If repeated, it does not work after the second time.

### ISSUE THREAD

**Issue by ru88s** [crashmax-dev/fireworks-js#74]
### Description

```js
const container = document.querySelector(".fireworks-container");
if (container) {
  const fireworks = new Fireworks(container, {
    acceleration: 1.0,
    delay: {
      min: 10,
      max: 100,
    },
    sound: {
      enabled: true,
      files: [
        "fireworks_0.mp3",
        "fireworks_1.mp3",
        "fireworks_2.mp3",
      ],
      volume: {
        min: 60,
        max: 80,
      },
    },
  });

  fireworks.start();
  setTimeout(() => {
    fireworks.stop();
  }, 10000);
}
```

If repeated, it does not work after the second time.
Sound is produced.

### Which package are you using?

@fireworks-js/react

### fireworks-js version

2.0.4

### Browser

chrome latest

**Comment by ru88s** [comment]
@crashmax-dev 

Yes, fireworks-js/react.
Thank you for the how to.

However, my web site has a chat page where fireworks go off when another user posts a message with fireworks.

If I use button.addEventListener, it only responds when I press the button myself.

Is there any other way to do this?

**Comment by crashmax-dev** [comment]
Unfortunately, the launch and the number of rockets launched is uncontrollable. :shrug: 
Maybe in the next major update we will add this support.

https://codesandbox.io/s/fireworks-js-react-ru88s-hxeeem?file=/src/App.tsx

**Comment by ru88s** [comment]
@crashmax-dev 
Thanks you for your quick support.
I will wait for the update.
