### ISSUE TITLE
How to make use of the API (start, waitStop) when using the Vue wrapper?

### ISSUE THREAD

**Issue by vesper8** [crashmax-dev/fireworks-js#87]
### Issue

I'm using the Vue wrapper and there doesn't seem to be a way to start the fireworks in "stopped" mode, there is a "autostart" option that seems to be missing.

I'd like to use waitStop in order to have a graceful finish after a few seconds of fireworks.

Would really appreciate an example that makes use of Vue that showcases a start/waitStop flow.

Many thanks! Love your plugin!

**Comment by crashmax-dev** [comment]
`@fireworks-js/vue` is not completed, but you can use the vanilla `fireworks-js` package.

[check out the current implementation under Vue.](https://github.com/crashmax-dev/fireworks-js/blob/master/packages/vue/src/fireworks.vue)
