### ISSUE TITLE
How to change the color of fireworks ？

### ISSUE THREAD

**Issue by ppttfish** [crashmax-dev/fireworks-js#92]
### Issue

Hello，What should I do if I want to change the color of the fireworks?

**Comment by crashmax-dev** [comment]
[hue](https://en.m.wikipedia.org/wiki/Hue) parameter has a minimum and a maximum, this value is calculated randomly from 0 to 360 at the start of each explosion firework

**Comment by ppttfish** [comment]
> [hue](https://en.m.wikipedia.org/wiki/Hue) parameter has a minimum and a maximum, this value is calculated randomly from 0 to 360 at the start of each explosion firework

What should I do If I want to customize the color

**Comment by crashmax-dev** [comment]
@ppttfish  https://github.com/crashmax-dev/fireworks-js#options
