### ISSUE TITLE
CDN link for v2.x?

### ISSUE THREAD

**Issue by BartmanEH** [crashmax-dev/fireworks-js#97]
### Description

what's the CDN link for v2?
the following link:
[https://unpkg.com/fireworks-js@latest/dist/fireworks.js](https://unpkg.com/fireworks-js@latest/dist/fireworks.js)
results in:
`Cannot find "/dist/fireworks.js" in fireworks-js@2.10.0`
and
[https://cdn.jsdelivr.net/npm/fireworks-js@latest/dist/fireworks.js](https://cdn.jsdelivr.net/npm/fireworks-js@latest/dist/fireworks.js)
links to v1.4.1

### Which package are you using?

fireworks-js

### fireworks-js version

1.4.1

### Browser

Chrome

**Comment by crashmax-dev** [comment]
Using a fixed version:
https://unpkg.com/fireworks-js@1.4.1
https://cdn.jsdelivr.net/npm/fireworks-js@1.4.1

or latest:
https://unpkg.com/fireworks-js@latest
https://cdn.jsdelivr.net/npm/fireworks-js@latest

**Comment by BartmanEH** [comment]
thanks for your help. I'm a bit of a hack so you'll have to bear with me as I move from 1.4.1 to 2.10.0. I'm using `https://cdn.jsdelivr.net/npm/fireworks-js@latest/dist/index.umd.js`
but getting:
`Uncaught TypeError: Fireworks is not a constructor`
for
`fireworks = new Fireworks(container,{});`

**Comment by crashmax-dev** [comment]
for some reason now it is in window
`new window['fireworks-js'].Fireworks(container)`

it was my mistake to rename the file from version 2.0. better to use fixed version in cdn's

**Comment by crashmax-dev** [comment]
upd:
![image](https://user-images.githubusercontent.com/15673111/210866404-8eec5872-2736-406d-a2d3-5257530d2146.png)

**Comment by crashmax-dev** [comment]
@BartmanEH 

the best way to used via cdn for latest version :shrug: 

![image](https://user-images.githubusercontent.com/15673111/210866650-a0d3a613-e7bd-4510-9f19-f948dd5df40e.png)

**Comment by crashmax-dev** [comment]
@BartmanEH https://codesandbox.io/s/loving-lederberg-4tdfiy?file=/src/index.ts

**Comment by BartmanEH** [comment]
OK, thanks to your help, I'm back to where I was: fireworks working but using v2.10.0 instead of v1.4.1

I think the readme needs an update to usage section to show:
`const fireworks = new Fireworks.default(container, { /* options */ })`
instead of
`const fireworks = new Fireworks(container, { /* options */ })`

but I still cannot get updateOptions to work. I moved it to after .start() but still `fireworks.updateOptions({ traceSpeed: 1 });` has no effect.

**Comment by BartmanEH** [comment]
OK, I think it's all working now. Thanks for your help. I do wish I could make is slower than traceSpeed = 1 :-)

**Comment by BartmanEH** [comment]
`fireworks.updateOptions({ traceSpeed: 1 });` in my application is no where near as slow as in your sandbox example.
